module Albums exposing (albums,Album)

import List

type alias Album = { title : String, artist : String, year : Int, mark : (Maybe String) }




entry m y t a = { title = t, artist = get_head a, year = y, mark = mk_mark m }

get_head l =
  case l of
    [] -> ""
    (x :: xs) -> x

mk_mark m = if m == "" then Nothing else Just m


albums = List.sortBy .year
  [ entry "﻿b" 1937 "King Of The Delta Blues Singers" ["Robert Johnson"]
  , entry "j" 1957 "Blue Train" ["John Coltrane"]
  , entry "s" 1957 "Body and Soul" ["Billie Holiday"]
  , entry "j" 1958 "The Atomic Mr Basie" ["Count Basie"]
  , entry "j" 1959 "Kind Of Blue" ["Miles Davis"]
  , entry "j" 1959 "Mingus Ah Um" ["Charles Mingus"]
  , entry "s" 1959 "What'd I Say" ["Ray Charles"]
  , entry "j" 1960 "Sketches of Spain" ["Gil Evans","Miles Davis"]
  , entry "s" 1960 "The Soul Of Ike & Tina Turner" ["Ike & Tina Turner"]
  , entry "s" 1961 "Genius + Soul = Jazz" ["Ray Charles"]
  , entry "" 1963 "In Dreams" ["Roy Orbison"]
  , entry "" 1963 "The Freewheelin' Bob Dylan" ["Bob Dylan"]
  , entry "" 1964 "A Hard Day's Night (Remastered)" ["The Beatles"]
  , entry "s" 1964 "Ain't That Good News" ["Sam Cooke"]
  , entry "" 1964 "Another Side Of Bob Dylan" ["Bob Dylan"]
  , entry "c" 1964 "I Walk the Line" ["Johnny Cash"]
  , entry "j" 1964 "It Might As Well Be Swing" ["Frank Sinatra","Count Basie"]
  , entry "" 1964 "The Times They Are A-Changin'" ["Bob Dylan"]
  , entry "j" 1965 "A Love Supreme" ["John Coltrane"]
  , entry "" 1965 "Bringing It All Back Home" ["Bob Dylan"]
  , entry "" 1965 "Highway 61 Revisited" ["Bob Dylan"]
  , entry "s" 1965 "Otis Blue" ["Otis Redding"]
  , entry "" 1965 "Rubber Soul (Remastered)" ["The Beatles"]
  , entry "" 1965 "The Great Otis Redding Sings Soul Ballads" ["Otis Redding"]
  , entry "" 1966 "Blonde On Blonde" ["Bob Dylan"]
  , entry "" 1966 "Live 1966 The Royal Albert Hall Concert The Bootleg Series Vol. 4" ["Bob Dylan"]
  , entry "" 1966 "Parsley, Sage, Rosemary And Thyme" ["Simon & Garfunkel"]
  , entry "" 1966 "Pet Sounds (Original Mono & Stereo Mix)" ["The Beach Boys"]
  , entry "" 1966 "River Deep-Mountain High" ["Ike & Tina Turner"]
  , entry "s" 1966 "The Exciting Wilson Pickett" ["Wilson Pickett"]
  , entry "s" 1966 "Wild Is The Wind" ["Nina Simone"]
  , entry "s" 1967 "Can You Dig It / I'm A Whole New Thing" ["Ural Thomas"]
  , entry "x" 1967 "Forever Changes (2015 Remaster)" ["Love"]
  , entry "" 1967 "John Wesley Harding" ["Bob Dylan"]
  , entry "" 1967 "Songs Of Leonard Cohen" ["Leonard Cohen"]
  , entry "" 1967 "Strange Days" ["The Doors"]
  , entry "" 1967 "The Doors" ["The Doors"]
  , entry "" 1967 "The Piper At The Gates Of Dawn [2011 - Remaster] (2011 Remastered Version)" ["Pink Floyd"]
  , entry "" 1967 "The Velvet Underground & Nico 45th Anniversary" ["The Velvet Underground","Nico"]
  , entry "" 1968 "A Saucerful Of Secrets (2011 Remaster)" ["Pink Floyd"]
  , entry "g" 1968 "Astral Weeks" ["Van Morrison"]
  , entry "gl" 1968 "At Folsom Prison" ["Johnny Cash"]
  , entry "g" 1968 "Bookends" ["Simon & Garfunkel"]
  , entry "b" 1968 "Cheap Thrills" ["Big Brother & The Holding Company","Janis Joplin"]
  , entry "" 1968 "Creedence Clearwater Revival (Expanded Edition)" ["Creedence Clearwater Revival"]
  , entry "g" 1968 "Electric Ladyland" ["Jimi Hendrix"]
  , entry "" 1968 "Music From Big Pink (Remastered)" ["The Band"]
  , entry "" 1968 "NBC-TV Special (Live)" ["Elvis Presley"]
  , entry "" 1968 "The Beatles (Remastered)" ["The Beatles"]
  , entry "" 1968 "Waiting for the Sun" ["The Doors"]
  , entry "s" 1968 "What A Wonderful World" ["Louis Armstrong"]
  , entry "g" 1969 "Abbey Road (Remastered)" ["The Beatles"]
  , entry "" 1969 "Bayou Country (Expanded Edition)" ["Creedence Clearwater Revival"]
  , entry "s" 1969 "Dusty In Memphis" ["Dusty Springfield"]
  , entry "" 1969 "Everybody Knows This Is Nowhere" ["Neil Young"]
  , entry "" 1969 "Five Leaves Left" ["Nick Drake"]
  , entry "" 1969 "Green River (Expanded Edition)" ["Creedence Clearwater Revival"]
  , entry "" 1969 "Hot Rats" ["Frank Zappa"]
  , entry "" 1969 "Led Zeppelin" ["Led Zeppelin"]
  , entry "" 1969 "Live From Batley Variety Club" ["Roy Orbison"]
  , entry "" 1969 "Nashville Skyline" ["Bob Dylan"]
  , entry "" 1969 "Songs From A Room" ["Leonard Cohen"]
  , entry "" 1969 "The Allman Brothers Band (Deluxe)" ["Allman Brothers Band"]
  , entry "" 1969 "The Soft Parade" ["The Doors"]
  , entry "" 1969 "Then Play On" ["Fleetwood Mac"]
  , entry "x" 1969 "Townes Van Zandt" ["Townes Van Zandt"]
  , entry "" 1969 "Ummagumma (2011 Remastered Version)" ["Pink Floyd"]
  , entry "" 1970 "After the Gold Rush (2009 Remaster)" ["Neil Young"]
  , entry "" 1970 "All Things Must Pass (Remastered 2014)" ["George Harrison"]
  , entry "" 1970 "Bitches Brew" ["Miles Davis"]
  , entry "g" 1970 "Cosmo's Factory" ["Creedence Clearwater Revival"]
  , entry "" 1970 "Curtis (Expanded Edition)" ["Curtis Mayfield"]
  , entry "g" 1970 "Deja Vu" ["Crosby, Stills, Nash & Young"]
  , entry "" 1970 "Free Your Mind..." ["Funkadelic"]
  , entry "s" 1970 "Funkadelic" ["Funkadelic"]
  , entry "" 1970 "Kiln House" ["Fleetwood Mac"]
  , entry "" 1970 "Let It Be (Remastered)" ["The Beatles"]
  , entry "" 1970 "Loaded (2015 Remaster)" ["The Velvet Underground"]
  , entry "" 1970 "Moondance" ["Van Morrison"]
  , entry "" 1970 "Morrison Hotel" ["The Doors"]
  , entry "" 1970 "New Morning" ["Bob Dylan"]
  , entry "s" 1970 "Psychedelic Shack" ["The Temptations"]
  , entry "" 1970 "Tea For The Tillerman (Remastered 2020)" ["Yusuf / Cat Stevens"]
  , entry "l" 1971 "4 Way Street" ["Crosby, Stills, Nash & Young"]
  , entry "l" 1971 "At Fillmore East" ["Allman Brothers Band"]
  , entry "" 1971 "Hunky Dory (2015 Remaster)" ["David Bowie"]
  , entry "" 1971 "John Prine" ["John Prine"]
  , entry "" 1971 "Just As I Am" ["Bill Withers"]
  , entry "" 1971 "L.A. Woman" ["The Doors"]
  , entry "" 1971 "Maggot Brain" ["Funkadelic"]
  , entry "" 1971 "Meddle (2011 Remastered Version)" ["Pink Floyd"]
  , entry "g" 1971 "Sticky Fingers (Remastered)" ["The Rolling Stones"]
  , entry "s" 1971 "There's A Riot Goin' On (Expanded Edition)" ["Sly & The Family Stone"]
  , entry "s" 1971 "What's Going On" ["Marvin Gaye"]
  , entry "" 1972 "All Directions" ["The Temptations"]
  , entry "" 1972 "Arriba Huentitan" ["Vicente Fern√°ndez"]
  , entry "l" 1972 "Elvis: As Recorded at Madison Square Garden (Live)" ["Elvis Presley"]
  , entry "g" 1972 "Harvest" ["Neil Young"]
  , entry "" 1972 "I'm Still in Love with You" ["Al Green"]
  , entry "s" 1972 "Let's Stay Together" ["Al Green"]
  , entry "x" 1972 "Naturally" ["J.J. Cale"]
  , entry "j" 1972 "On The Corner" ["Miles Davis"]
  , entry "" 1972 "Paul Simon" ["Paul Simon"]
  , entry "" 1972 "Pink Moon" ["Nick Drake"]
  , entry "" 1972 "Sail Away (Expanded & Remastered Edition)" ["Randy Newman"]
  , entry "" 1972 "Saint Dominic's Preview" ["Van Morrison"]
  , entry "" 1972 "Sonneveld" ["Wim Sonneveld"]
  , entry "s" 1972 "Superfly" ["Curtis Mayfield"]
  , entry "" 1972 "The Rise and Fall of Ziggy Stardust and the Spiders from Mars (2012 Remaster)" ["David Bowie"]
  , entry "" 1972 "Transformer" ["Lou Reed"]
  , entry "" 1973 "Berlin" ["Lou Reed"]
  , entry "" 1973 "Closing Time" ["Tom Waits"]
  , entry "" 1973 "Closing Time (Remastered)" ["Tom Waits"]
  , entry "" 1973 "Head Hunters" ["Herbie Hancock"]
  , entry "g" 1973 "Innervisions" ["Stevie Wonder"]
  , entry "" 1973 "Prokofiev: Romeo and Juliet" ["Sergei Prokofiev"]
  , entry "" 1973 "Solid Air (Remastered)" ["John Martyn"]
  , entry "" 1973 "The Dark Side Of The Moon (2011 Remastered Version)" ["Pink Floyd"]
  , entry "l" 1974 "..It's Too Late to Stop Now…" ["Van Morrison"]
  , entry "" 1974 "Diamond Dogs" ["David Bowie"]
  , entry "" 1974 "Get Up With It" ["Miles Davis"]
  , entry "" 1974 "On the Beach" ["Neil Young"]
  , entry "" 1974 "Planet Waves" ["Bob Dylan"]
  , entry "" 1974 "The Heart Of Saturday Night (Remastered)" ["Tom Waits"]
  , entry "s" 1974 "They Say I'm Different" ["Betty Davis"]
  , entry "" 1974 "Veedon Fleece" ["Van Morrison"]
  , entry "" 1975 "An Evening With John Denver" ["John Denver"]
  , entry "g" 1975 "Blood On The Tracks" ["Bob Dylan"]
  , entry "" 1975 "Born To Run" ["Bruce Springsteen"]
  , entry "" 1975 "Fleetwood Mac" ["Fleetwood Mac"]
  , entry "" 1975 "Harry Sacksioni: Gitaar" ["Harry Sacksioni"]
  , entry "" 1975 "Nighthawks At The Diner (Remastered)" ["Tom Waits"]
  , entry "s" 1975 "The Heat Is On" ["The Isley Brothers"]
  , entry "j" 1975 "The Koln Concert" ["Keith Jarrett"]
  , entry "" 1975 "Tonight's the Night" ["Neil Young"]
  , entry "" 1975 "Wish You Were Here (2011 Remastered Version)" ["Pink Floyd"]
  , entry "" 1975 "Young Americans" ["David Bowie"]
  , entry "" 1975 "Zuma" ["Neil Young"]
  , entry "" 1976 "Crystal Ball" ["Styx"]
  , entry "" 1976 "Desire" ["Bob Dylan"]
  , entry "" 1976 "Eggs & Sausage - Remastered" ["Tom Waits"]
  , entry "" 1976 "Live Nassau Coliseum '76" ["David Bowie"]
  , entry "g" 1976 "Small Change" ["Tom Waits"]
  , entry "" 1976 "Songs In The Key Of Life" ["Stevie Wonder"]
  , entry "g" 1976 "Station to Station (2016 Remaster)" ["David Bowie"]
  , entry "" 1977 "Heroes (2017 Remaster)" ["David Bowie"]
  , entry "g" 1977 "Animals (2011 Remastered Version)" ["Pink Floyd"]
  , entry "x" 1977 "Marquee Moon" ["Television"]
  , entry "g" 1977 "Rumours" ["Fleetwood Mac"]
  , entry "" 1977 "Talking Heads '77 (Deluxe Version)" ["Talking Heads"]
  , entry "" 1977 "The Clash (Remastered)" ["The Clash"]
  , entry "" 1978 "Adventure" ["Television"]
  , entry "" 1978 "Blue Valentine (Remastered)" ["Tom Waits"]
  , entry "g" 1978 "Dire Straits (Remastered)" ["Dire Straits"]
  , entry "" 1978 "More Songs About Buildings and Food (Deluxe Version)" ["Talking Heads"]
  , entry "" 1978 "Parallel Lines (Remastered)" ["Blondie"]
  , entry "" 1978 "Stage (Live 2005 Remaster)" ["David Bowie"]
  , entry "" 1979 "Communique" ["Dire Straits"]
  , entry "" 1979 "Drums And Wires" ["XTC"]
  , entry "" 1979 "Fear of Music (Deluxe Version)" ["Talking Heads"]
  , entry "" 1979 "Joe's Garage Acts I, II & III" ["Frank Zappa"]
  , entry "" 1979 "Lodger (2017 Remaster)" ["David Bowie"]
  , entry "" 1979 "London Calling (Remastered)" ["The Clash"]
  , entry "" 1979 "Off the Wall" ["Michael Jackson"]
  , entry "" 1979 "Orchestral Favorites" ["Frank Zappa"]
  , entry "" 1979 "Sheik Yerbouti" ["Frank Zappa"]
  , entry "" 1979 "Slow Train Coming" ["Bob Dylan"]
  , entry "" 1979 "The Wall (Remastered)" ["Pink Floyd"]
  , entry "" 1979 "Tusk (2015 Remaster)" ["Fleetwood Mac"]
  , entry "" 1979 "Unknown Pleasures" ["Joy Division"]
  , entry "" 1980 "Boy (Remastered)" ["U2"]
  , entry "" 1980 "Closer" ["Joy Division"]
  , entry "" 1980 "Colossal Youth" ["Young Marble Giants"]
  , entry "" 1980 "Heartattack And Vine" ["Tom Waits"]
  , entry "" 1980 "Making Movies" ["Dire Straits"]
  , entry "" 1980 "Remain in Light (Deluxe Version)" ["Talking Heads"]
  , entry "" 1980 "The Blues Brothers Original Motion Picture Soundtrack" ["The Blues Brothers"]
  , entry "" 1980 "The River" ["Bruce Springsteen"]
  , entry "" 1981 "October (Remastered)" ["U2"]
  , entry "" 1981 "Street Songs" ["Rick James"]
  , entry "" 1982 "Avalon" ["Roxy Music"]
  , entry "" 1982 "Junkyard" ["The Birthday Party"]
  , entry "" 1982 "Love Over Gold" ["Dire Straits"]
  , entry "" 1982 "Love Over Gold (Remastered)" ["Dire Straits"]
  , entry "g" 1982 "Nebraska" ["Bruce Springsteen"]
  , entry "" 1982 "Pornography" ["The Cure"]
  , entry "" 1982 "Thriller" ["Michael Jackson"]
  , entry "" 1983 "Hootenanny (Expanded)" ["The Replacements"]
  , entry "" 1983 "Let's Dance (1999 Remaster)" ["David Bowie"]
  , entry "" 1983 "London Symphony Orchestra, Vols. I & II" ["Frank Zappa","London Symphony Orchestra"]
  , entry "g" 1983 "Murmur" ["R.E.M."]
  , entry "" 1983 "Power Corruption and Lies" ["New Order"]
  , entry "" 1983 "Speaking in Tongues (Deluxe Version)" ["Talking Heads"]
  , entry "" 1983 "Swordfishtrombones" ["Tom Waits"]
  , entry "" 1983 "Synchronicity (Remastered 2003)" ["The Police"]
  , entry "" 1983 "The Final Cut (2011 Remastered Version)" ["Pink Floyd"]
  , entry "l" 1983 "Under A Blood Red Sky (Remastered)" ["U2"]
  , entry "" 1983 "War (Remastered)" ["U2"]
  , entry "l" 1984 "Alchemy: Dire Straits Live" ["Dire Straits"]
  , entry "" 1984 "Born In The U.S.A." ["Bruce Springsteen"]
  , entry "" 1984 "Double Nickels on the Dime" ["Minutemen"]
  , entry "x" 1984 "Let It Be (Expanded)" ["The Replacements"]
  , entry "" 1984 "Purple Rain" ["Prince"]
  , entry "" 1984 "Reckoning" ["R.E.M."]
  , entry "l" 1984 "Stop Making Sense (Live)" ["Talking Heads"]
  , entry "" 1984 "The Unforgettable Fire (Deluxe Edition Remastered)" ["U2"]
  , entry "" 1985 "Bad Moon Rising" ["Sonic Youth"]
  , entry "" 1985 "Boys And Girls" ["Bryan Ferry"]
  , entry "" 1985 "Brothers In Arms" ["Dire Straits"]
  , entry "" 1985 "Fables Of The Reconstruction" ["R.E.M."]
  , entry "" 1985 "Meat Is Murder" ["The Smiths"]
  , entry "" 1985 "Rain Dogs" ["Tom Waits"]
  , entry "g" 1986 "Blood And Chocolate" ["Elvis Costello & The Attractions"]
  , entry "" 1986 "Brotherhood (Collector's Edition)" ["New Order"]
  , entry "" 1986 "Graceland" ["Paul Simon"]
  , entry "" 1986 "Graceland (25th Anniversary Deluxe Edition)" ["Paul Simon"]
  , entry "" 1986 "The Queen Is Dead" ["The Smiths"]
  , entry "" 1986 "True Stories" ["Talking Heads"]
  , entry "" 1987 "A Momentary Lapse Of Reason (2011 Remastered Version)" ["Pink Floyd"]
  , entry "r" 1987 "Appetite For Destruction" ["Guns N' Roses"]
  , entry "" 1987 "Bad (Remastered)" ["Michael Jackson"]
  , entry "" 1987 "Document (R.E.M. No. 5)" ["R.E.M."]
  , entry "" 1987 "Franks Wild Years" ["Tom Waits"]
  , entry "" 1987 "Music for the Masses" ["Depeche Mode"]
  , entry "x" 1987 "Sister" ["Sonic Youth"]
  , entry "" 1987 "Tango In the Night (Deluxe)" ["Fleetwood Mac"]
  , entry "g" 1987 "The Joshua Tree" ["U2"]
  , entry "" 1988 "Daydream Nation (Remastered Original Album)" ["Sonic Youth"]
  , entry "" 1988 "I'm Your Man" ["Leonard Cohen"]
  , entry "" 1988 "Immigres" ["Youssou N'Dour"]
  , entry "" 1988 "Rattle And Hum" ["U2"]
  , entry "" 1988 "Surfer Rosa (Remastered)" ["Pixies"]
  , entry "" 1988 "Tender Prey (2010 Remastered Version)" ["Nick Cave & The Bad Seeds"]
  , entry "" 1989 "Black & White Night" ["Roy Orbison"]
  , entry "" 1989 "Disintegration (Remastered)" ["The Cure"]
  , entry "" 1989 "Doolittle" ["Pixies"]
  , entry "x" 1989 "Mystery Girl" ["Roy Orbison"]
  , entry "" 1989 "Niemand In De Stad" ["De Dijk"]
  , entry "" 1989 "Pretty Hate Machine" ["Nine Inch Nails"]
  , entry "" 1989 "Tchaikovsky: Piano Concerto No.1" ["Tchaikovsky"]
  , entry "" 1989 "Technique" ["New Order"]
  , entry "" 1990 "Het Beste Van Boudewijn De Groot" ["Boudewijn de Groot"]
  , entry "" 1990 "Is Dit Nu Later" ["Stef Bos"]
  , entry "" 1990 "Still Got The Blues" ["Gary Moore"]
  , entry "" 1990 "Violator" ["Depeche Mode"]
  , entry "" 1991 "Achtung Baby" ["U2"]
  , entry "" 1991 "Blue Lines (2012 Mix/Master)" ["Massive Attack"]
  , entry "" 1991 "Dangerous" ["Michael Jackson"]
  , entry "" 1991 "Mississippi Lad" ["Teddy Edwards"]
  , entry "" 1991 "Nevermind (Remastered)" ["Nirvana"]
  , entry "" 1991 "Out Of Time" ["R.E.M."]
  , entry "g" 1991 "Ten" ["Pearl Jam"]
  , entry "" 1991 "The Early Years Vol. 1" ["Tom Waits"]
  , entry "" 1991 "The Soul Cages" ["Sting"]
  , entry "r" 1991 "Use Your Illusion I" ["Guns N' Roses"]
  , entry "gr" 1991 "Use Your Illusion II" ["Guns N' Roses"]
  , entry "" 1992 "Bone Machine" ["Tom Waits"]
  , entry "" 1992 "Gorky" ["Gorki"]
  , entry "l" 1992 "Live At Wembley Stadium" ["Queen"]
  , entry "x" 1992 "Palomine" ["Bettie Serveert"]
  , entry "" 1992 "Propeller" ["Guided By Voices"]
  , entry "e" 1992 "Selected Ambient Works 85-92" ["Aphex Twin"]
  , entry "" 1992 "Slanted And Enchanted" ["Pavement"]
  , entry "l" 1992 "Unplugged (Live)" ["Eric Clapton"]
  , entry "" 1993 "August And Everything After" ["Counting Crows"]
  , entry "" 1993 "Hij Leeft" ["Gorki"]
  , entry "" 1993 "In Utero - 20th Anniversary Remaster" ["Nirvana"]
  , entry "" 1993 "Pablo Honey" ["Radiohead"]
  , entry "g" 1993 "Siamese Dream (2011 - Remaster)" ["The Smashing Pumpkins"]
  , entry "" 1993 "Ten Summoner's Tales" ["Sting"]
  , entry "" 1993 "The Early Years Vol. 2" ["Tom Waits"]
  , entry "" 1993 "The Yellow Shark" ["Frank Zappa"]
  , entry "" 1993 "There Is No-One What Will Take Care Of You" ["Palace Brothers"]
  , entry "" 1993 "Unplugged" ["Neil Young"]
  , entry "" 1993 "Vs." ["Pearl Jam"]
  , entry "" 1993 "Wild Wood" ["Paul Weller"]
  , entry "" 1993 "Zooropa" ["U2"]
  , entry "" 1994 "American Recordings" ["Johnny Cash"]
  , entry "" 1994 "Crooked Rain Crooked Rain" ["Pavement"]
  , entry "" 1994 "De Ontmoeting" ["Frank Boeijen"]
  , entry "e" 1994 "Dubnobasswithmyheadman (20th Anniversary Remaster)" ["Underworld"]
  , entry "" 1994 "Dummy" ["Portishead"]
  , entry "" 1994 "Grace" ["Jeff Buckley"]
  , entry "" 1994 "Le Onde" ["Ludovico Einaudi"]
  , entry "" 1994 "Let Love In (2011 Remastered Version)" ["Nick Cave & The Bad Seeds"]
  , entry "" 1994 "Live in Santa Monica '72" ["David Bowie"]
  , entry "l" 1994 "MTV Unplugged In New York" ["Nirvana"]
  , entry "x" 1994 "Out Of Range" ["Ani DiFranco"]
  , entry "" 1994 "The Great Subconscious Club" ["K's Choice"]
  , entry "" 1994 "Throwing Copper" ["Live"]
  , entry "" 1994 "Vitalogy" ["Pearl Jam"]
  , entry "" 1994 "Welcome To The Cruel World" ["Ben Harper"]
  , entry "" 1994 "Worst Case Scenario" ["dEUS"]
  , entry "" 1995 "Ainda: Original Motion Picture Soundtrack From Lisbon Story" ["Madredeus"]
  , entry "" 1995 "Alien Lanes" ["Guided By Voices"]
  , entry "" 1995 "Boulevard (The Complete Series)" ["St Germain"]
  , entry "" 1995 "Elliott Smith" ["Elliott Smith"]
  , entry "" 1995 "HIStory - PAST, PRESENT AND FUTURE - BOOK I" ["Michael Jackson"]
  , entry "" 1995 "Made In Heaven (2011 Remaster)" ["Queen"]
  , entry "h" 1995 "Maxinquaye" ["Tricky"]
  , entry "" 1995 "Mellon Collie And The Infinite Sadness" ["The Smashing Pumpkins"]
  , entry "" 1995 "Original Soundtracks 1" ["Passengers"]
  , entry "" 1995 "Paradise In Me" ["K's Choice"]
  , entry "" 1995 "Pulse" ["Pink Floyd"]
  , entry "" 1995 "The Bends" ["Radiohead"]
  , entry "" 1995 "Timeless" ["Goldie"]
  , entry "" 1995 "Viva Last Blues" ["Palace Music"]
  , entry "" 1996 "American II: Unchained" ["Johnny Cash"]
  , entry "" 1996 "Endtroducing....." ["DJ Shadow"]
  , entry "" 1996 "If You're Feeling Sinister" ["Belle and Sebastian"]
  , entry "" 1996 "Interstate 8" ["Modest Mouse"]
  , entry "" 1996 "Lamb" ["Lamb"]
  , entry "" 1996 "Ludovico Einaudi: Le onde" ["Ludovico Einaudi"]
  , entry "" 1996 "Monstertje" ["Gorki"]
  , entry "" 1996 "Murder Ballads (2011 Remastered Version)" ["Nick Cave & The Bad Seeds"]
  , entry "" 1996 "Odelay" ["Beck"]
  , entry "" 1996 "Pinkerton" ["Weezer"]
  , entry "" 1996 "This Is a Long Drive for Someone with Nothing to Think About" ["Modest Mouse"]
  , entry "" 1997 "Acda & De Munnik" ["Acda en de Munnik"]
  , entry "" 1997 "Buena Vista Social Club" ["Buena Vista Social Club"]
  , entry "" 1997 "Either/Or" ["Elliott Smith"]
  , entry "" 1997 "F# A#" ["Godspeed You! Black Emperor"]
  , entry "" 1997 "Homework" ["Daft Punk"]
  , entry "" 1997 "Homogenic" ["Bjork"]
  , entry "" 1997 "I Can Hear The Heart Beating As One" ["Yo La Tengo"]
  , entry "" 1997 "OK Computer" ["Radiohead"]
  , entry "" 1997 "Pop" ["U2"]
  , entry "" 1997 "The Boatman's Call (2011 Remastered Version)" ["Nick Cave & The Bad Seeds"]
  , entry "" 1997 "The Lonesome Crowded West" ["Modest Mouse"]
  , entry "" 1997 "Time Out Of Mind" ["Bob Dylan"]
  , entry "" 1997 "Wyclef Jean presents The Carnival featuring Refugee Allstars (feat. Refugee All Stars)" ["Wyclef Jean"]
  , entry "" 1998 "American Water" ["Silver Jews"]
  , entry "" 1998 "Cocoon Crash" ["K's Choice"]
  , entry "" 1998 "I Paint Pictures On A Wedding Dress" ["Zita Swoon"]
  , entry "" 1998 "I See A Darkness" ["Bonnie Prince Billy"]
  , entry "" 1998 "Mezzanine" ["Massive Attack"]
  , entry "e" 1998 "Moon Safari" ["Air"]
  , entry "" 1998 "Music Has The Right To Children" ["Boards of Canada"]
  , entry "" 1998 "Naar Huis" ["Acda en de Munnik"]
  , entry "" 1998 "Pilgrim" ["Eric Clapton"]
  , entry "" 1998 "The Very Best of Solomon Burke" ["Solomon Burke"]
  , entry "" 1998 "XO" ["Elliott Smith"]
  , entry "x" 1999 "Emergency & I" ["Dismemberment Plan"]
  , entry "h" 1999 "Fear Of Fours" ["Lamb"]
  , entry "x" 1999 "Industrial Silence" ["Madrugada"]
  , entry "x" 1999 "Magnolia (Music from the Motion Picture)" ["Aimee Mann"]
  , entry "" 1999 "Mule Variations" ["Tom Waits"]
  , entry "" 1999 "Summerteeth" ["Wilco"]
  , entry "" 1999 "The Ideal Crash" ["dEUS"]
  , entry "" 1999 "The Soft Bulletin" ["The Flaming Lips"]
  , entry "" 1999 "Wildernis" ["Alex Roeka"]
  , entry "" 1999 "Agaetis byrjun" ["Sigur Ros"]
  , entry "" 2000 "All That You Can't Leave Behind" ["U2"]
  , entry "c" 2000 "American III: Solitary Man" ["Johnny Cash"]
  , entry "" 2000 "Bachelor No. 2 (Or, The Last Remains of the Dodo)" ["Aimee Mann"]
  , entry "" 2000 "Building Nothing Out Of Something" ["Modest Mouse"]
  , entry "" 2000 "Heartbreaker" ["Ryan Adams"]
  , entry "" 2000 "Incredible Jazz Guitar" ["Wes Montgomery"]
  , entry "" 2000 "Kid A" ["Radiohead"]
  , entry "" 2000 "Lift Your Skinny Fists Like Antennas to Heaven" ["Godspeed You! Black Emperor"]
  , entry "x" 2000 "Natural History" ["I Am Kloot"]
  , entry "" 2000 "Novastar" ["Novastar"]
  , entry "" 2000 "O Brother, Where Art Thou? (Original Motion Picture Soundtrack)" ["Various Artists"]
  , entry "b" 2000 "Riding with the King" ["Eric Clapton","B.B. King"]
  , entry "" 2000 "Since I Left You" ["The Avalanches"]
  , entry "" 2000 "Stories From The City, Stories From The Sea" ["PJ Harvey"]
  , entry "x" 2000 "The Moon & Antarctica" ["Modest Mouse"]
  , entry "" 2000 "Thirteen Tales From Urban Bohemia" ["The Dandy Warhols"]
  , entry "" 2000 "Tourist (Remastered)" ["St Germain"]
  , entry "" 2000 "Voodoo" ["D'Angelo"]
  , entry "" 2001 "Amnesiac" ["Radiohead"]
  , entry "" 2001 "Asleep In The Back" ["Elbow"]
  , entry "" 2001 "Discovery" ["Daft Punk"]
  , entry "" 2001 "I Might Be Wrong" ["Radiohead"]
  , entry "" 2001 "Is This It" ["The Strokes"]
  , entry "" 2001 "Love And Theft" ["Bob Dylan"]
  , entry "" 2001 "Oh, Inverted World" ["The Shins"]
  , entry "x" 2001 "Pergola" ["JOHAN"]
  , entry "x" 2001 "Poses" ["Rufus Wainwright"]
  , entry "" 2001 "Simple Things" ["Zero 7"]
  , entry "" 2001 "Stay Human" ["Michael Franti & Spearhead"]
  , entry "" 2001 "The National" ["The National"]
  , entry "" 2001 "Those Who Tell the Truth Shall Die, Those Who Tell the Truth Shall Live Forever" ["Explosions In The Sky"]
  , entry "" 2001 "Used Songs (1973-1980)" ["Tom Waits"]
  , entry "" 2002 "A Series of Sneaks" ["Spoon"]
  , entry "x" 2002 "Alice" ["Tom Waits"]
  , entry "" 2002 "All Hail West Texas (Remastered)" ["The Mountain Goats"]
  , entry "" 2002 "American IV: The Man Comes Around" ["Johnny Cash"]
  , entry "" 2002 "Blood Money" ["Tom Waits"]
  , entry "s" 2002 "Don't Give Up On Me" ["Solomon Burke"]
  , entry "" 2002 "Groeten Uit Maaiveld" ["Acda en de Munnik"]
  , entry "" 2002 "Lost In Space" ["Aimee Mann"]
  , entry "l" 2002 "One More Car, One More Rider (Live)" ["Eric Clapton"]
  , entry "" 2002 "Sea Change" ["Beck"]
  , entry "" 2002 "Songs For The Deaf" ["Queens of the Stone Age"]
  , entry "" 2002 "Spinvis" ["Spinvis"]
  , entry "" 2002 "The Definitive Collection" ["Little River Band"]
  , entry "" 2002 "Turn On The Bright Lights" ["Interpol"]
  , entry "" 2003 "Angel Malherido" ["El Barrio"]
  , entry "x" 2003 "Chutes Too Narrow" ["The Shins"]
  , entry "" 2003 "Donker En Licht" ["Stef Bos"]
  , entry "" 2003 "Feast of Wire" ["Calexico"]
  , entry "" 2003 "Hail To the Thief" ["Radiohead"]
  , entry "" 2003 "In Time: The Best Of R.E.M. 1988-2003" ["R.E.M."]
  , entry "" 2003 "Lo mas lejos a tu lado" ["Fito y Fitipaldis"]
  , entry "" 2003 "Master And Everyone" ["Bonnie Prince Billy"]
  , entry "" 2003 "NYC Man" ["Lou Reed"]
  , entry "" 2003 "Nieuwegein Aan Zee" ["Spinvis"]
  , entry "" 2003 "Room On Fire" ["The Strokes"]
  , entry "" 2003 "Sad Songs for Dirty Lovers" ["The National"]
  , entry "" 2003 "Sad Songs for Dirty Lovers (2021 Remaster)" ["The National"]
  , entry "x" 2003 "Thirteenth Step" ["A Perfect Circle"]
  , entry "l" 2003 "Thirteenth Step - Live" ["A Perfect Circle"]
  , entry "" 2003 "Veneer" ["Jose Gonzalez"]
  , entry "" 2003 "Waiting for the Moon" ["Tindersticks"]
  , entry "" 2003 "Youth And Young Manhood" ["Kings of Leon"]
  , entry "" 2004 "7 Seconds: The Best Of Youssou N'Dour" ["Youssou N'Dour"]
  , entry "" 2004 "A Song About A Girls" ["Zita Swoon"]
  , entry "" 2004 "Animal Serenade" ["Lou Reed"]
  , entry "" 2004 "Another Lonely Soul" ["Novastar"]
  , entry "" 2004 "Antics" ["Interpol"]
  , entry "l" 2004 "Baron Von Bullshit Rides Again" ["Modest Mouse"]
  , entry "" 2004 "Blueberry Boat" ["The Fiery Furnaces"]
  , entry "" 2004 "Bows + Arrows" ["The Walkmen"]
  , entry "" 2004 "Cherry Tree" ["The National"]
  , entry "" 2004 "Franz Ferdinand" ["Franz Ferdinand"]
  , entry "" 2004 "Funeral" ["Arcade Fire"]
  , entry "l" 2004 "Live at St. Ann's Warehouse" ["Aimee Mann"]
  , entry "" 2004 "Made To Love Magic" ["Nick Drake"]
  , entry "x" 2004 "Our Endless Numbered Days" ["Iron & Wine"]
  , entry "" 2004 "Real Gone (Remastered)" ["Tom Waits"]
  , entry "" 2004 "The Essential Kris Kristofferson" ["Kris Kristofferson"]
  , entry "" 2004 "Trouble" ["Ray LaMontagne"]
  , entry "" 2004 "When It Falls" ["Zero 7"]
  , entry "" 2005 "Alligator" ["The National"]
  , entry "" 2005 "Another Day" ["Racoon"]
  , entry "" 2005 "Another Day (Deluxe Edition)" ["Racoon"]
  , entry "" 2005 "Apologies To The Queen Mary" ["Wolf Parade"]
  , entry "" 2005 "Black Mountain" ["Black Mountain"]
  , entry "" 2005 "Black Mountain (10th Anniversary Deluxe Edition)" ["Black Mountain"]
  , entry "" 2005 "Daft Punk Is Playing at My House" ["LCD Soundsystem"]
  , entry "" 2005 "Dagen Van Gras, Dagen Van Stro" ["Spinvis"]
  , entry "" 2005 "Fair and Square" ["John Prine"]
  , entry "" 2005 "Gods and Monsters" ["I Am Kloot"]
  , entry "" 2005 "Here We Go, Stereo" ["Racoon"]
  , entry "x" 2005 "I'm Wide Awake, It's Morning" ["Bright Eyes"]
  , entry "x" 2005 "Illinois" ["Sufjan Stevens"]
  , entry "" 2005 "LCD Soundsystem" ["LCD Soundsystem"]
  , entry "" 2005 "Lullabies To Paralyze" ["Queens of the Stone Age"]
  , entry "" 2005 "Minimum - Maximum" ["Kraftwerk"]
  , entry "" 2005 "Naturally" ["Sharon Jones & The Dap-Kings"]
  , entry "" 2005 "Picaresque" ["The Decemberists"]
  , entry "" 2005 "Pajaros En La Cabeza" ["Amaral"]
  , entry "" 2005 "Secret Meeting" ["The National"]
  , entry "" 2005 "Superwolf" ["Matt Sweeney","Bonnie Prince Billy"]
  , entry "" 2005 "The Budos Band" ["The Budos Band"]
  , entry "" 2005 "The Campfire Headphase" ["Boards of Canada"]
  , entry "" 2005 "The Singles" ["Basement Jaxx"]
  , entry "" 2005 "The Sunset Tree" ["The Mountain Goats"]
  , entry "" 2005 "Till Monkeys Fly" ["Racoon"]
  , entry "" 2005 "Twin Cinema" ["The New Pornographers"]
  , entry "" 2006 "Are You Ready For Freddie?" ["Freddie King"]
  , entry "" 2006 "As" ["Frank Boeijen"]
  , entry "" 2006 "Back To Black (Deluxe Edition)" ["Amy Winehouse"]
  , entry "" 2006 "Blue Note Trip 2: Sunset/Sunrise" ["Various Artists"]
  , entry "x" 2006 "Dreams" ["The Whitest Boy Alive"]
  , entry "" 2006 "Everything All The Time" ["Band of Horses"]
  , entry "" 2006 "I Am Not Afraid Of You And I Will Beat Your Ass" ["Yo La Tengo"]
  , entry "" 2006 "Meds" ["Placebo"]
  , entry "" 2006 "Modern Times" ["Bob Dylan"]
  , entry "" 2006 "Movements" ["Booka Shade"]
  , entry "" 2006 "Nineteeneighties" ["Grant-Lee Phillips"]
  , entry "" 2006 "Orphans: Brawlers, Bawlers & Bastards" ["Tom Waits"]
  , entry "" 2006 "Stone Cold Ohio" ["Little Axe"]
  , entry "x" 2006 "The Crane Wife" ["The Decemberists"]
  , entry "" 2006 "The Eraser" ["Thom Yorke"]
  , entry "" 2006 "The Essential Roy Orbison" ["Roy Orbison"]
  , entry "" 2006 "Whatever People Say I Am, That's What I'm Not" ["Arctic Monkeys"]
  , entry "" 2007 "Alive 2007" ["Daft Punk"]
  , entry "" 2007 "All Hour Cymbals" ["Yeasayer"]
  , entry "g" 2007 "Boxer" ["The National"]
  , entry "" 2007 "Country Ghetto" ["JJ Grey","Mofro"]
  , entry "" 2007 "Grinderman" ["Grinderman"]
  , entry "x" 2007 "In Our Nature" ["Jose Gonzalez"]
  , entry "" 2007 "In Rainbows" ["Radiohead"]
  , entry "x" 2007 "Into The Wild (Music For The Motion Picture)" ["Eddie Vedder"]
  , entry "" 2007 "Knives Don't Have Your Back" ["Emily Haines"]
  , entry "" 2007 "Last Night of the Proms" ["Royal Philharmonic Orchestra"]
  , entry "" 2007 "Neon Bible" ["Arcade Fire"]
  , entry "" 2007 "Our Love To Admire" ["Interpol"]
  , entry "" 2007 "Release The Stars" ["Rufus Wainwright"]
  , entry "" 2007 "Rumpelzirkus" ["Kalabrese"]
  , entry "" 2007 "Soul Queen" ["Aretha Franklin"]
  , entry "" 2007 "Sound of Silver" ["LCD Soundsystem"]
  , entry "" 2007 "The Abattoir Blues Tour (Live)" ["Nick Cave & The Bad Seeds"]
  , entry "r" 2007 "The Red Album" ["Baroness"]
  , entry "" 2007 "The Shepherd's Dog" ["Iron & Wine"]
  , entry "" 2007 "The Stage Names" ["Okkervil River"]
  , entry "" 2007 "We Were Dead Before The Ship Even Sank" ["Modest Mouse"]
  , entry "" 2008 "A Skin, A Night + The Virginia EP" ["The National"]
  , entry "" 2008 "Aardige Jongens" ["Boeijen Hofstede Vrienten"]
  , entry "" 2008 "Accelerate" ["R.E.M."]
  , entry "" 2008 "Creedence Clearwater Revival - Best Of (Deluxe)" ["Creedence Clearwater Revival"]
  , entry "" 2008 "Dig, Lazarus, Dig!!!" ["Nick Cave & The Bad Seeds"]
  , entry "r" 2008 "Fantasy Black Channel" ["Late of the Pier"]
  , entry "" 2008 "Fleet Foxes" ["Fleet Foxes"]
  , entry "x" 2008 "For Emma, Forever Ago" ["Bon Iver"]
  , entry "x" 2008 "Hercules & Love Affair" ["Hercules & Love Affair"]
  , entry "" 2008 "I, Flathead" ["Ry Cooder"]
  , entry "" 2008 "Kitty Daisy & Lewis" ["Kitty, Daisy & Lewis"]
  , entry "" 2008 "Lie Down In The Light" ["Bonnie Prince Billy"]
  , entry "" 2008 "Shallow Grave" ["The Tallest Man On Earth"]
  , entry "" 2008 "The '59 Sound" ["The Gaslight Anthem"]
  , entry "" 2008 "The Midnight Organ Fight" ["Frightened Rabbit"]
  , entry "" 2008 "The Seldom Seen Kid" ["Elbow"]
  , entry "" 2008 "Thriller 25 Super Deluxe Edition" ["Michael Jackson"]
  , entry "" 2008 "Vampire Weekend" ["Vampire Weekend"]
  , entry "" 2008 "What Grabs Ya?" ["Triggerfinger"]
  , entry "" 2009 "45:33 Remixes" ["LCD Soundsystem"]
  , entry "" 2009 "Absynthe Minded" ["Absynthe Minded"]
  , entry "" 2009 "Blood Bank" ["Bon Iver"]
  , entry "" 2009 "For Your Entertainment" ["Adam Lambert"]
  , entry "l" 2009 "Glitter And Doom Live (Remastered)" ["Tom Waits"]
  , entry "x" 2009 "Gorilla Manor" ["Local Natives"]
  , entry "" 2009 "Hometowns" ["The Rural Alberta Advantage"]
  , entry "x" 2009 "Isbells" ["Isbells"]
  , entry "" 2009 "It Don't Get No Better Than This: Essential Recordings" ["Solomon Burke"]
  , entry "" 2009 "Live from Madison Square Garden" ["Eric Clapton","Steve Winwood"]
  , entry "ex" 2009 "Moderat (Deluxe Version)" ["Moderat"]
  , entry "" 2009 "Never Be Scared / Don't Be A Hero" ["Moss"]
  , entry "x" 2009 "Reservoir" ["Fanfarlo"]
  , entry "x" 2009 "Sometimes I Wish We Were An Eagle" ["Bill Callahan"]
  , entry "" 2009 "The Best of the Black President" ["Fela Kuti"]
  , entry "" 2009 "The Life of the World to Come" ["The Mountain Goats"]
  , entry "" 2009 "The Pains of Being Pure At Heart" ["The Pains Of Being Pure At Heart"]
  , entry "" 2009 "Tijdgeest" ["Harry Sacksioni"]
  , entry "" 2009 "Veckatimest" ["Grizzly Bear"]
  , entry "" 2009 "Wait For Evolution" ["De Staat"]
  , entry "x" 2009 "Wolfgang Amadeus Phoenix" ["Phoenix"]
  , entry "" 2009 "xx" ["The xx"]
  , entry "" 2010 "Adrenaline" ["Harry Sacksioni"]
  , entry "" 2010 "Becoming A Jackal" ["Villagers"]
  , entry "" 2010 "Before Today" ["Ariel Pink"]
  , entry "" 2010 "Brothers" ["The Black Keys"]
  , entry "" 2010 "Contra" ["Vampire Weekend"]
  , entry "" 2010 "Cosmogramma" ["Flying Lotus"]
  , entry "" 2010 "Familial" ["Philip Selway"]
  , entry "" 2010 "Future Weather" ["The War On Drugs"]
  , entry "" 2010 "Halcyon Digest" ["Deerhunter"]
  , entry "" 2010 "High Violet" ["The National"]
  , entry "" 2010 "Hold On Tight" ["Solomon Burke","De Dijk"]
  , entry "" 2010 "King of the Beach" ["Wavves"]
  , entry "l" 2010 "London Sessions" ["LCD Soundsystem"]
  , entry "" 2010 "Mahler: Symphony No. 2, Resurrection (Live)" ["Gustav Mahler"]
  , entry "" 2010 "Mexican Spaghetti Western (Bonus Edition)" ["Chingon"]
  , entry "x" 2010 "Odd Blood" ["Yeasayer"]
  , entry "" 2010 "On Claws" ["I Am Oak"]
  , entry "" 2010 "Plastic Beach" ["Gorillaz"]
  , entry "" 2010 "Seadrift Soundmachine" ["Blaudzun"]
  , entry "" 2010 "Sometimes The Blues Is Just A Passing Bird" ["The Tallest Man On Earth"]
  , entry "" 2010 "The Monitor" ["Titus Andronicus"]
  , entry "" 2010 "The Suburbs" ["Arcade Fire"]
  , entry "x" 2010 "The Wild Hunt" ["The Tallest Man On Earth"]
  , entry "" 2010 "This Is Happening" ["LCD Soundsystem"]
  , entry "ex" 2010 "Time for Us" ["Nicolas Jaar"]
  , entry "x" 2010 "Total Life Forever" ["Foals"]
  , entry "" 2011 "Apocalypse" ["Bill Callahan"]
  , entry "x" 2011 "Applause" ["Balthazar"]
  , entry "" 2011 "Ashes & Fire" ["Ryan Adams"]
  , entry "" 2011 "Bad As Me (Deluxe Edition)" ["Tom Waits"]
  , entry "" 2011 "Bon Iver" ["Bon Iver"]
  , entry "x" 2011 "Days" ["Real Estate"]
  , entry "" 2011 "El Camino" ["The Black Keys"]
  , entry "" 2011 "Helplessness Blues" ["Fleet Foxes"]
  , entry "" 2011 "Kaputt" ["Destroyer"]
  , entry "" 2011 "Knife Man" ["AJJ"]
  , entry "" 2011 "Lonely Boy" ["The Black Keys"]
  , entry "s" 2011 "No Time For Dreaming" ["Charles Bradley"]
  , entry "" 2011 "No Time For Dreaming (Instrumentals)" ["Charles Bradley"]
  , entry "" 2011 "On the Water" ["Future Islands"]
  , entry "" 2011 "Rome" ["Danger Mouse","Daniele Luppi"]
  , entry "" 2011 "Slave Ambient" ["The War On Drugs"]
  , entry "" 2011 "Smoke Ring For My Halo" ["Kurt Vile"]
  , entry "" 2011 "So Beautiful or So What" ["Paul Simon"]
  , entry "" 2011 "Space Is Only Noise" ["Nicolas Jaar"]
  , entry "" 2011 "TKOL RMX 1234567" ["Radiohead"]
  , entry "" 2011 "TOTAL" ["New Order"]
  , entry "" 2011 "The King of Limbs" ["Radiohead"]
  , entry "x" 2011 "W H O K I L L" ["Tune-Yards"]
  , entry "" 2011 "Wolfroy Goes To Town" ["Bonnie Prince Billy"]
  , entry "" 2011 "build a rocket boys!" ["Elbow"]
  , entry "x" 2012 "Allelujah! Don't Bend! Ascend!" ["Godspeed You! Black Emperor"]
  , entry "" 2012 "An Awesome Wave" ["alt-J"]
  , entry "" 2012 "Attack On Memory" ["Cloud Nothings"]
  , entry "" 2012 "Boys & Girls" ["Alabama Shakes"]
  , entry "" 2012 "Broken Brights" ["Angus Stone"]
  , entry "" 2012 "Celebration Rock" ["Japandroids"]
  , entry "" 2012 "Cobra Juicy" ["Black Moth Super Rainbow"]
  , entry "" 2012 "Coexist" ["The xx"]
  , entry "" 2012 "Gegroefd" ["Alex Roeka"]
  , entry "" 2012 "Gold on the Ceiling" ["The Black Keys"]
  , entry "" 2012 "Het Beste Van Peter Koelewijn" ["Peter Koelewijn"]
  , entry "" 2012 "Jake Bugg" ["Jake Bugg"]
  , entry "" 2012 "Kill For Love" ["Chromatics"]
  , entry "" 2012 "Last of a Dyin' Breed (Special Edition)" ["Lynyrd Skynyrd"]
  , entry "" 2012 "Locked Down" ["Dr. John"]
  , entry "" 2012 "Mr. M" ["Lambchop"]
  , entry "" 2012 "My Head Is An Animal" ["Of Monsters and Men"]
  , entry "" 2012 "Port Of Morrow" ["The Shins"]
  , entry "" 2012 "Rachmaninov: Piano Concerto No.2" ["Sergei Rachmaninoff"]
  , entry "" 2012 "Shallow Bed (Deluxe Version)" ["Dry the River"]
  , entry "" 2012 "Shields" ["Grizzly Bear"]
  , entry "" 2012 "Stoalin'" ["Isbells"]
  , entry "" 2012 "Sweet Heart Sweet Light" ["Spiritualized"]
  , entry "" 2012 "Swing Lo Magellan" ["Dirty Projectors"]
  , entry "" 2012 "Tempest" ["Bob Dylan"]
  , entry "" 2013 "AM" ["Arctic Monkeys"]
  , entry "" 2013 "Alle Singles" ["Acda en de Munnik"]
  , entry "" 2013 "Brothers And Sisters (Deluxe Edition)" ["Allman Brothers Band"]
  , entry "" 2013 "Cupid Deluxe" ["Blood Orange"]
  , entry "" 2013 "Dream River" ["Bill Callahan"]
  , entry "" 2013 "Fade" ["Yo La Tengo"]
  , entry "" 2013 "Half Of Where You Live" ["Gold Panda"]
  , entry "" 2013 "Holy Fire" ["Foals"]
  , entry "" 2013 "II" ["Moderat"]
  , entry "" 2013 "If You Wait (Deluxe Version)" ["London Grammar"]
  , entry "" 2013 "Kveikur" ["Sigur Ros"]
  , entry "" 2013 "La Leyenda Del Tiempo" ["Camaron De La Isla"]
  , entry "" 2013 "Live from KCRW" ["Nick Cave & The Bad Seeds"]
  , entry "" 2013 "Mala" ["Devendra Banhart"]
  , entry "" 2013 "Modern Vampires of the City" ["Vampire Weekend"]
  , entry "x" 2013 "Pedestrian Verse" ["Frightened Rabbit"]
  , entry "g" 2013 "Push the Sky Away" ["Nick Cave & The Bad Seeds"]
  , entry "" 2013 "Random Access Memories" ["Daft Punk"]
  , entry "" 2013 "Reflektor" ["Arcade Fire"]
  , entry "" 2013 "Set the House on Fire" ["Moddi"]
  , entry "" 2013 "Settle" ["Disclosure"]
  , entry "x" 2013 "Silence Yourself" ["Savages"]
  , entry "" 2013 "The Bones Of What You Believe" ["CHVRCHES"]
  , entry "" 2013 "Trouble Will Find Me" ["The National"]
  , entry "" 2013 "We Are the 21st Century Ambassadors of Peace & Magic" ["Foxygen"]
  , entry "" 2013 "Woman" ["Rhye"]
  , entry "" 2014 "All That Jazz, Vol. 9: Duke Ellington‚ The Cotton Club Years (Remastered 2014)" ["Duke Ellington"]
  , entry "b" 2014 "Anthology" ["Howlin' Wolf"]
  , entry "" 2014 "Atlas" ["Real Estate"]
  , entry "" 2014 "Badillac" ["Together Pangea"]
  , entry "" 2014 "Bruckner: Symphony No. 8 (Robert Haas Version) [Live]" ["Anton Bruckner"]
  , entry "" 2014 "Bryce Dessner: St. Carolyn By The Sea / Jonny Greenwood: Suite From There Will Be Blood" ["Copenhagen Phil","Andre de Ridder"]
  , entry "x" 2014 "Caustic Love" ["Paolo Nutini"]
  , entry "l" 2014 "Caustic Love (Live and In Session)" ["Paolo Nutini"]
  , entry "" 2014 "Emmaar" ["Tinariwen"]
  , entry "" 2014 "Here and Nowhere Else" ["Cloud Nothings"]
  , entry "" 2014 "Kiasmos" ["Kiasmos"]
  , entry "g" 2014 "Let It Be... Naked (Remastered)" ["The Beatles"]
  , entry "" 2014 "Live In Dublin" ["Leonard Cohen"]
  , entry "" 2014 "Lost In The Dream" ["The War On Drugs"]
  , entry "" 2014 "Nikki Nack" ["Tune-Yards"]
  , entry "" 2014 "Popular Problems" ["Leonard Cohen"]
  , entry "" 2014 "Salad Days" ["Mac DeMarco"]
  , entry "x" 2014 "Singles" ["Future Islands"]
  , entry "" 2014 "Spotify Sessions: Live at Sxsw 2014" ["St. Paul & The Broken Bones"]
  , entry "" 2014 "Syro" ["Aphex Twin"]
  , entry "" 2014 "Terms of My Surrender" ["John Hiatt"]
  , entry "" 2014 "They Want My Soul" ["Spoon"]
  , entry "" 2014 "Turn Blue" ["The Black Keys"]
  , entry "" 2014 "Ultraviolence (Deluxe)" ["Lana Del Rey"]
  , entry "" 2014 "live at jodrell bank" ["Elbow"]
  , entry "" 2014 "the long goodbye (lcd soundsystem live at madison square garden)" ["LCD Soundsystem"]
  , entry "" 2015 "Afrodeezia" ["Marcus Miller"]
  , entry "" 2015 "Asunder, Sweet and Other Distress" ["Godspeed You! Black Emperor"]
  , entry "" 2015 "Best Of" ["Ike & Tina Turner"]
  , entry "" 2015 "Billie's Choice" ["Billie Holiday"]
  , entry "" 2015 "Carrie & Lowell" ["Sufjan Stevens"]
  , entry "" 2015 "Currents" ["Tame Impala"]
  , entry "" 2015 "Depression Cherry" ["Beach House"]
  , entry "" 2015 "El patio 40 Aniversario" ["Triana"]
  , entry "e" 2015 "Elaenia" ["Floating Points"]
  , entry "" 2015 "Esencia (En Vivo En El Teatro Real)" ["El Barrio"]
  , entry "" 2015 "Fading Frontier" ["Deerhunter"]
  , entry "" 2015 "Filament" ["eighth blackbird","Bryce Dessner"]
  , entry "j" 2014 "No Deal" ["Melanie De Biasio"]
  , entry "c" 2015 "High on Tulsa Heat" ["John Moreland"]
  , entry "" 2015 "I Love You, Honeybear" ["Father John Misty"]
  , entry "" 2015 "I'm the Man to Be" ["EL VY"]
  , entry "e" 2015 "In Colour" ["Jamie xx"]
  , entry "" 2015 "Nathaniel Rateliff & The Night Sweats" ["Nathaniel Rateliff & The Night Sweats","Nathaniel Rateliff"]
  , entry "" 2015 "No Life for Me" ["Wavves","Cloud Nothings"]
  , entry "" 2015 "Return to the Moon" ["EL VY"]
  , entry "" 2015 "Silent Ivy Hotel" ["EL VY"]
  , entry "" 2015 "Sound & Color" ["Alabama Shakes"]
  , entry "" 2015 "Sparks" ["Beach House"]
  , entry "" 2015 "Star Wars" ["Wilco"]
  , entry "" 2015 "Strangers to Ourselves" ["Modest Mouse"]
  , entry "j" 2015 "Sylva" ["Snarky Puppy","Metropole Orkest"]
  , entry "" 2015 "The Most Lamentable Tragedy" ["Titus Andronicus"]
  , entry "c" 2015 "Traveller" ["Chris Stapleton"]
  , entry "x" 2015 "White Water" ["The Slow Show"]
  , entry "x" 2015 "b'lieve i'm goin down..." ["Kurt Vile"]
  , entry "" 2016 "22, A Million" ["Bon Iver"]
  , entry "" 2016 "A Moon Shaped Pool" ["Radiohead"]
  , entry "" 2016 "A Sailor's Guide to Earth" ["Sturgill Simpson"]
  , entry "" 2016 "Adore Life" ["Savages"]
  , entry "" 2016 "Amen & Goodbye" ["Yeasayer"]
  , entry "" 2016 "Are You Serious" ["Andrew Bird"]
  , entry "x" 2016 "Blackstar" ["David Bowie"]
  , entry "" 2016 "Breadcrumbs" ["The Perennials"]
  , entry "" 2016 "Cardan" ["Agar Agar"]
  , entry "s" 2016 "Changes" ["Charles Bradley"]
  , entry "" 2016 "Day of the Dead" ["Various Artists"]
  , entry "" 2016 "Daydreaming" ["Radiohead"]
  , entry "" 2016 "Fixion" ["trentemoller"]
  , entry "" 2016 "Her Tape #1" ["Her"]
  , entry "" 2016 "Human Performance" ["Parquet Courts"]
  , entry "" 2016 "I Had a Dream That You Were Mine" ["Hamilton Leithauser","Rostam"]
  , entry "" 2016 "Love & Hate" ["Michael Kiwanuka"]
  , entry "" 2016 "Michael Gielen Edition, Vol. 2: Bruckner's Symphonies Nos. 1-9" ["Anton Bruckner"]
  , entry "" 2016 "Miss Marionette" ["The Perennials"]
  , entry "" 2016 "Next Thing" ["Frankie Cosmos"]
  , entry "" 2016 "Night On the Sun" ["Modest Mouse"]
  , entry "" 2016 "Painting of a Panic Attack (Deluxe Edition)" ["Frightened Rabbit"]
  , entry "" 2016 "Singing Saw" ["Kevin Morby"]
  , entry "" 2016 "Sirens" ["Nicolas Jaar"]
  , entry "" 2016 "Skeleton Tree" ["Nick Cave & The Bad Seeds"]
  , entry "" 2016 "Spotify Sessions" ["Car Seat Headrest"]
  , entry "" 2016 "Stranger To Stranger" ["Paul Simon"]
  , entry "" 2016 "Teens of Denial" ["Car Seat Headrest"]
  , entry "" 2016 "The Ship" ["Brian Eno"]
  , entry "" 2016 "Unsongs" ["Moddi"]
  , entry "" 2016 "Wildflower" ["The Avalanches"]
  , entry "x" 2016 "You Want It Darker" ["Leonard Cohen"]
  , entry "" 2017 "A Boy From Tupelo: The Complete 1953-1955 Recordings" ["Elvis Presley"]
  , entry "" 2017 "A Crow Looked at Me" ["Mount Eerie"]
  , entry "" 2017 "A Deeper Understanding" ["The War On Drugs"]
  , entry "" 2017 "Aromanticism" ["Moses Sumney"]
  , entry "" 2017 "Beast Epic" ["Iron & Wine"]
  , entry "" 2017 "Bhangra Pirates" ["Red Baraat"]
  , entry "" 2017 "Big Bad Luv" ["John Moreland"]
  , entry "" 2017 "Blurred" ["Kiasmos"]
  , entry "" 2017 "Bruckner: Symphony No. 8" ["Anton Bruckner"]
  , entry "" 2017 "Carrie & Lowell Live" ["Sufjan Stevens"]
  , entry "" 2017 "Crack-Up" ["Fleet Foxes"]
  , entry "" 2017 "Elwan" ["Tinariwen"]
  , entry "" 2017 "Everything Now" ["Arcade Fire"]
  , entry "" 2017 "Goths" ["The Mountain Goats"]
  , entry "" 2017 "Hang" ["Foxygen"]
  , entry "" 2017 "I Promise" ["Radiohead"]
  , entry "" 2017 "I See You" ["The xx"]
  , entry "" 2017 "Live At My Father's Place, WLIR-FM Broadcast, Roslyn NY, 10th October 1977 (Remastered)" ["Tom Waits"]
  , entry "" 2017 "Love What Survives" ["Mount Kimbie"]
  , entry "" 2017 "Luciferian Towers" ["Godspeed You! Black Emperor"]
  , entry "" 2017 "OK Computer OKNOTOK 1997 2017" ["Radiohead"]
  , entry "" 2017 "On Hold (Jamie xx Remix)" ["The xx"]
  , entry "" 2017 "Painted Ruins" ["Grizzly Bear"]
  , entry "" 2017 "Planetarium" ["James McAlister","Bryce Dessner"]
  , entry "" 2017 "Poor David's Almanack" ["David Rawlings"]
  , entry "" 2017 "R. Strauss: Le bourgeois gentilhomme Suite & Ariadne auf Naxos, Symphony-suite" ["Richard Strauss"]
  , entry "" 2017 "RELAXER" ["alt-J"]
  , entry "" 2017 "Science Fiction" ["Brand New"]
  , entry "" 2017 "Signs of Life" ["Arcade Fire"]
  , entry "" 2017 "Sleep Well Beast" ["The National"]
  , entry "" 2017 "Tchaikovsky: Symphony No. 6 in B Minor, Op. 74 Pathetique" ["Tchaikovsky"]
  , entry "" 2017 "The Far Field" ["Future Islands"]
  , entry "" 2017 "The OOZ" ["King Krule"]
  , entry "" 2017 "Turn Out the Lights" ["Julien Baker"]
  , entry "" 2017 "american dream" ["LCD Soundsystem"]
  , entry "l" 1968 "68 Comeback Special " ["Elvis Presley"]
  , entry "" 2018 "2012 - 2017" ["Against All Logic"]
  , entry "" 2018 "50 Years - Don't Stop" ["Fleetwood Mac"]
  , entry "" 2018 "7" ["Beach House"]
  , entry "" 2018 "A Brief Inquiry Into Online Relationships" ["The 1975"]
  , entry "" 2018 "Bohemian Rhapsody (The Original Soundtrack)" ["Queen"]
  , entry "" 2018 "Bottle It In" ["Kurt Vile"]
  , entry "l" 2018 "Boxer (Live in Brussels)" ["The National"]
  , entry "" 1947 "Cannot Be Satisfied: The Very Best Of Muddy Waters" ["Muddy Waters"]
  , entry "" 2018 "Echo Collective Plays Amnesiac" ["Echo Collective"]
  , entry "" 2018 "Freedom" ["Amen Dunes"]
  , entry "" 2018 "Hardest TIme" ["Red Bird Hollow","Aaron Dessner"]
  , entry "" 2018 "I can feel you creep into my private life" ["Tune-Yards"]
  , entry "m" 2018 "Joy as an Act of Resistance." ["IDLES"]
  , entry "" 2018 "Medicaid Fraud Dogg" ["Parliament"]
  , entry "" 2018 "More Blood, More Tracks: The Bootleg Series, Vol. 14 (Sampler)" ["Bob Dylan"]
  , entry "" 2018 "Ordinary Corrupt Human Love" ["Deafheaven"]
  , entry "" 2018 "REDUXER" ["alt-J"]
  , entry "" 2018 "Safe In The Hands of Love" ["Yves Tumor"]
  , entry "" 2018 "Singularity" ["Jon Hopkins"]
  , entry "c" 2018 "The Tree of Forgiveness" ["John Prine"]
  , entry "" 2018 "True Meanings" ["Paul Weller"]
  , entry "" 2018 "Your Queen Is A Reptile" ["Sons Of Kemet"]
  , entry "" 2019 "ANIMA" ["Thom Yorke"]
  , entry "" 2019 "Amir (Deluxe)" ["Tamino"]
  , entry "" 2019 "Blackwattle Caprices" ["Jacob Cordover"]
  , entry "" 2019 "Ghosteen" ["Nick Cave & The Bad Seeds"]
  , entry "" 2019 "I Am Easy to Find" ["The National"]
  , entry "" 2019 "In League with Dragons" ["The Mountain Goats"]
  , entry "" 2019 "Juicy Sonic Magic (Live in Berkeley September 24-25 2018)" ["The National"]
  , entry "" 2019 "My Finest Work Yet" ["Andrew Bird"]
  , entry "" 2019 "Noche Andaluza" ["Isabel Martinez"]
  , entry "" 2019 "Norman Fucking Rockwell!" ["Lana Del Rey"]
  , entry "" 2019 "SOUND & FURY" ["Sturgill Simpson"]
  , entry "" 2019 "Shepherd in a Sheepskin Vest" ["Bill Callahan"]
  , entry "" 2019 "So that you might hear me" ["Bear's Den"]
  , entry "" 2019 "Tchaikovsky: Symphony No. 6 Pathetique" ["Tchaikovsky"]
  , entry "" 2019 "Two Hands" ["Big Thief"]
  , entry "" 2019 "Western Stars" ["Bruce Springsteen"]
  , entry "x" 2019 "When We Are Inhuman" ["Bonnie Prince Billy","Bryce Dessner"]
  , entry "" 2019 "Your Capricious Soul" ["Michael Stipe"]
  , entry "" 2019 "i,i" ["Bon Iver"]
  , entry "" 2020 "40 Melodies" ["Ibrahim Maalouf"]
  , entry "" 2020 "7-Inches for Planned Parenthood, Vol. 2: Pt. 2" ["Various Artists"]
  , entry "" 2020 "7.6.9.6." ["Spinvis"]
  , entry "x" 2020 "A Hero's Death" ["Fontaines D.C."]
  , entry "" 2020 "AUATC" ["Bon Iver"]
  , entry "" 2020 "As Long As You Are" ["Future Islands"]
  , entry "" 2020 "Best Of Paco Paco" ["Paco Paco"]
  , entry "" 2020 "Brothers (Deluxe Remastered Anniversary Edition)" ["The Black Keys"]
  , entry "xh" 2020 "Circles" ["Mac Miller"]
  , entry "" 2020 "Cosmic Dancer" ["Nick Cave"]
  , entry "" 2020 "Drive to the Ocean" ["Michael Stipe"]
  , entry "" 2020 "Gold Record" ["Bill Callahan"]
  , entry "" 2020 "Got To Be Tough" ["Toots & The Maytals"]
  , entry "" 2020 "Guitar Works of Francisco Tarrega" ["Francisco Tarrega","Philip Hemmo"]
  , entry "" 2020 "Have We Met" ["Destroyer"]
  , entry "" 2020 "Heaven To A Tortured Mind" ["Yves Tumor"]
  , entry "c" 2020 "How Lucky" ["Kurt Vile"]
  , entry "" 2020 "Idiot Prayer (Nick Cave Alone at Alexandra Palace)" ["Nick Cave & The Bad Seeds"]
  , entry "" 2020 "MONOVISION" ["Ray LaMontagne"]
  , entry "" 2020 "Man from the Future" ["Polyrhythmics"]
  , entry "" 2020 "McCartney III" ["Paul McCartney"]
  , entry "" 2020 "Melee" ["Dogleg"]
  , entry "" 2020 "Mordechai" ["Khruangbin"]
  , entry "" 2020 "Never Tear Us Apart" ["The National"]
  , entry "" 2020 "No Time For Love Like Now" ["Michael Stipe","Big Red Machine"]
  , entry "" 2020 "Notes On A Conditional Form" ["The 1975"]
  , entry "" 2020 "Prokofiev Top 10" ["Sergei Prokofiev"]
  , entry "" 2020 "Rollin' and Tumblin'" ["Eric Clapton","B.B. King"]
  , entry "" 2020 "Rough and Rowdy Ways" ["Bob Dylan"]
  , entry "" 2020 "Serpentine Prison" ["Matt Berninger"]
  , entry "" 2020 "Shore" ["Fleet Foxes"]
  , entry "" 2020 "Silver Ladders" ["Mary Lattimore"]
  , entry "" 2020 "Song Machine, Season One: Strange Timez (Deluxe)" ["Gorillaz"]
  , entry "x" 2020 "Songs for Pierre Chuvin" ["The Mountain Goats"]
  , entry "" 2020 "Speed, Sound, Lonely KV (ep)" ["Kurt Vile"]
  , entry "" 2020 "Starting Over" ["Chris Stapleton"]
  , entry "" 2020 "Suite: April 2020" ["Brad Mehldau"]
  , entry "" 2020 "Summerlong" ["Rose City Band"]
  , entry "" 2020 "The New Abnormal" ["The Strokes"]
  , entry "" 2020 "Untitled (Black Is)" ["SAULT"]
  , entry "" 2020 "Untitled (Rise)" ["SAULT"]
  , entry "" 2020 "instrumentals" ["Adrianne Lenker"]
  , entry "x" 2020 "songs" ["Adrianne Lenker"]
  , entry "" 2021 "Afrique Victime" ["Mdou Moctar"]
  , entry "" 2021 "Any Shape You Take" ["Indigo De Souza"]
  , entry "xj" 2021 "Black To The Future" ["Sons Of Kemet"]
  , entry "" 2021 "Blind Date Party" ["Bill Callahan","Bonnie Prince Billy"]
  , entry "" 2021 "Delta Kream" ["The Black Keys"]
  , entry "" 2021 "I Dont Live Here Anymore" ["The War On Drugs"]
  , entry "" 2021 "Ignorance" ["The Weather Station"]
  , entry "" 2021 "Imagine" ["Tommy Emmanuel"]
  , entry "" 2021 "KID A MNESIA" ["Radiohead"]
  , entry "" 2021 "Licorice Pizza (Original Motion Picture Soundtrack)" ["Various Artists"]
  , entry "" 2021 "Raise The Roof (Deluxe Edition)" ["Robert Plant","Alison Krauss"]
  , entry "" 2021 "Rufus Wainwright and Amsterdam Sinfonietta (Live)" ["Rufus Wainwright","Amsterdam Sinfonietta"]
  , entry "" 2021 "Serpentine Prison (Deluxe Edition)" ["Matt Berninger"]
  , entry "" 2021 "Spijt Is Iets Voor Later" ["Racoon"]
  , entry "" 2021 "Superwolves" ["Matt Sweeney","Bonnie Prince Billy"]
  , entry "c" 2021 "The Ballad of Dood & Juanita" ["Sturgill Simpson"]
  , entry "" 2021 "The Monitor (2021 Remaster)" ["Titus Andronicus"]
  , entry "" 2021 "Vulture Prince" ["Arooj Aftab"]
  , entry "r" 2021 "Welfare Jazz" ["Viagra Boys"]
  , entry "x" 2022 "A Light for Attracting Attention" ["The Smile"]
  , entry "" 2022 "Alpha Zulu" ["Phoenix"]
  , entry "x" 2022 "Ants From Up There" ["Black Country, New Road"]
  , entry "x" 2022 "Atemporal" ["El Barrio"]
  , entry "" 2022 "Blood Money (Anniversary Edition)" ["Tom Waits"]
  , entry "" 2022 "Blue Rev" ["Alvvays"]
  , entry "" 2022 "Boat Songs" ["MJ Lenderman"]
  , entry "" 2022 "Dragon New Warm Mountain I Believe In You" ["Big Thief"]
  , entry "" 2022 "Dropout Boogie" ["The Black Keys"]
  , entry "" 2022 "Formentera" ["Metric"]
  , entry "" 2022 "GOLD" ["Alabaster DePlume"]
  , entry "" 2022 "God's Away On Business (Live)" ["Tom Waits"]
  , entry "" 2022 "King Of Hearts" ["Roy Orbison"]
  , entry "" 2022 "LABYRINTHITIS" ["Destroyer"]
  , entry "" 2022 "Last Night In The Bittersweet" ["Paolo Nutini"]
  , entry "" 2022 "Mendelssohn: Song without Words, Op. 109" ["Felix Mendelssohn","Sheku Kanneh-Mason"]
  , entry "" 2022 "Skinty Fia" ["Fontaines D.C."]
  , entry "" 2022 "Sons Of" ["Sam Prekop","John McEntire"]
  , entry "" 2022 "Table Top Joe (Live)" ["Tom Waits"]
  , entry "" 2022 "The Car" ["Arctic Monkeys"]
  , entry "l" 2022 "The Smile (Live at Montreux Jazz Festival, July 2022)" ["The Smile"]
  , entry "" 2022 "Things Are Great" ["Band of Horses"]
  , entry "" 2022 "Underwater" ["Ludovico Einaudi"]
  , entry "" 2022 "WE" ["Arcade Fire"]
  , entry "x" 2022 "Weather Alive" ["Beth Orton"]
  , entry "" 2022 "Weird Goodbyes (feat. Bon Iver)" ["The National"]
  , entry "" 2022 "Windveren" ["Boudewijn de Groot"]
  , entry "" 2023 "Bending Hectic" ["The Smile"]
  , entry "" 2023 "First Two Pages of Frankenstein" ["The National"]
  , entry "" 2023 "Folkocracy" ["Rufus Wainwright"]
  , entry "" 2023 "Hackney Diamonds" ["The Rolling Stones"]
  , entry "" 2023 "Javelin" ["Sufjan Stevens"]
  , entry "" 2023 "Keeping Secrets Will Destroy You" ["Bonnie Prince Billy"]
  , entry "" 2023 "Laugh Track" ["The National"]
  , entry "x" 2023 "My Back Was A Bridge For You To Cross" ["ANOHNI"]
  , entry "x" 2023 "Praise A Lord Who Chews But Which Does Not Consume (Or Simply, Hot Between Worlds)" ["Yves Tumor"]
  , entry "" 2023 "Rufus Wainwright (25th Anniversary Edition)" ["Rufus Wainwright"]
  , entry "" 2023 "Tropic Morning News" ["The National"]
  , entry "x" 2024 "Heavy Metal" ["Cameron Winter"]
  , entry "x" 2025 "Getting Killed" ["Geese"]
  , entry "x" 2025 "New threats from the soul" ["Ryan Davis & the Roadhouse band"]
  , entry "g" 1976 "Zoot Allures" ["Frank Zappa"]
  , entry "l" 1971 "Live at Massey Hall" ["Neil Young"]
  , entry "x" 2024 "Clouds in the sky will always be there for me" ["Porridge Radio"]
  , entry "" 2025 "Glutton for punishment" ["Heartworms"]
  , entry "l" 1970 "Get Yer Ya-Ya's Out!" ["The Rolling Stones"]
  , entry "l" 1973 "A Crowded Street (Live London 73)" ["Bill Whithers"]
  , entry "l" 1971 "Aretha Live at Fillmore West" ["Aretha Franklin"]
  , entry "g" 2006 "Rather Ripped" ["Sonic Youth"]
  , entry "j" 1947 "Satcho At Symphony Hall" ["Louis Armstrong"]
  , entry "j" 1956 "Ella and Louis" ["Ella Fitzgerald","Louis Armstrong"]
  , entry "s" 1958 "At Newport" ["Mahalia Jackson"]
  , entry "l" 1974 "Live European Tour" ["Billy Preston"]
  , entry "x" 1986 "The Colour of Spring" ["Talk talk"]
  , entry "l" 1976 "The last waltz" ["The Band"]
  , entry "e" 2005 "Nite version (15 year anniversary edition)" ["Soulwax"]
  , entry "x" 1999 "69 Love Songs" ["The magnetic fields"]
  , entry "j" 1959 "Everybody Diggs Bill Evans" ["Bill Evans"]
  , entry "j" 2024 "The way out of easy" ["Jeff Parker"] ]
